#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <time.h>

#define N_CHILDREN 5
#define N_PIPES 6

int main()
{
   // Array of 6 pipes
   int pipec[6][2], i;
   pid_t pid[5];

   // Create pipes and assure they were created successfully
   for (i = 0; i < N_PIPES; i++)
   {
      if (pipe(pipec[i]) == -1)
      {
         printf("Error creating pipe\n");
         exit(EXIT_FAILURE);
      }
   }

   for (i = 0; i < N_CHILDREN; i++)
   {
      // Create child process and assure it was created successfully
      if ((pid[i] = fork()) == -1)
      {
         printf("Error creating child process\n");
         exit(EXIT_FAILURE);
      }
      else if (pid[i] == 0)
      { // Child process

         // Generate random number between 1 and 500
         srand((unsigned)time(NULL) * getpid());
         int random_number = (rand() % 500) + 1;
         printf("Child process %d generated %d \n\n", getpid(), random_number);

         // Close write end of the pipe and Read random number from pipe
         close(pipec[i][1]);
         int received_number;
         read(pipec[i][0], &received_number, sizeof(received_number));
         close(pipec[i][0]);

         // Print the number recieved from the parent process.
         printf("Child process %d received %d \n\n", getpid(), received_number);

         // Compare the two numbers and write to the next pipe the bigger number
         if (random_number > received_number)
         {
            // Close read end of the pipe and Write random number to pipe
            close(pipec[i + 1][0]);
            write(pipec[i + 1][1], &random_number, sizeof(random_number));
            close(pipec[i + 1][1]);
         }
         else
         {
            // Close read end of the pipe and Write random number to pipe
            close(pipec[i + 1][0]);
            write(pipec[i + 1][1], &received_number, sizeof(received_number));
            close(pipec[i + 1][1]);
         }

         exit(EXIT_SUCCESS);
      }
   }

   // Parent process

   // Generate random number between 1 and 500
   srand((unsigned)time(NULL) * getpid());
   int random_number = (rand() % 500) + 1;

   // Close read end of the pipe and Write random number to pipe
   close(pipec[0][0]);
   write(pipec[0][1], &random_number, sizeof(random_number));
   close(pipec[0][1]);

   // Print the number generated by the parent process
   printf("Parent process %d generated %d \n\n", getpid(), random_number);

   // Wait for all child processes to finish
   for (i = 0; i < 5; i++)
   {
      wait(NULL);
   }

   // Close write end of the pipe and Read max number from pipe
   close(pipec[5][1]);
   int max_number;
   read(pipec[5][0], &max_number, sizeof(max_number));
   close(pipec[5][0]);

   // Print the max number
   printf("The max number that was generated is %d \n\n", max_number);

   return 0;
}